# Parameters
#db-url: jdbc:postgresql://localhost:5432/postgres
#db-username: postgres
#db-password: root
#cors-whitelist: http://localhost:3000

# Actuator
management.endpoints.web.exposure.include: info,health,httptrace

# Server
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
  servlet:
    context-path: "/rest"

# Database
spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect