name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for DockerHub auth"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for DockerHub auth"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform lint
        run: |
          cd infra/
          terraform -chdir=deploy/ init -backend=false
          terraform -chdir=setup/ init -backend=false
          terraform -chdir=setup/ validate
          terraform -chdir=setup/ fmt -check
          terraform -chdir=deploy/ validate
          terraform -chdir=deploy/ fmt -check